/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import dao.JdbcConnection;
import dao.ProductDAO;
import java.sql.Connection;
/**
 *
 * @author kirbymckenzie
 */
public final class MainMenu extends javax.swing.JFrame {

    private final ProductDAO dao;
    private String url = "jdbc:h2:tcp://localhost/~/project;IFEXISTS=TRUE";
    
    boolean tester;
    Connection dbCon;
    
    

    
    public MainMenu(ProductDAO dao) {
        initComponents();
        this.dao = dao;
        tester = JdbcConnection.testConnection();
       connectDB();
    }
    
    // connect to DB,
    public void connectDB(){
        if (tester = true){
     
       dbCon = JdbcConnection.getConnection(url); 
        setStatusLabel(true);
        
        }else {
            setStatusLabel(false);
        }
    }
   
   
    public void setStatusLabel(boolean statusEntered) {
    //Shows the variable statusEntered has been received 
    //System.out.println(statusEntered);

    //Not working
    if (statusEntered = true){
        lblConnectionStatus.setText("Connected");
    } else {
        lblConnectionStatus.setText("Not Connected");
    }

    //Used this to check if the label receives the data. It does.
        //String status = lblConnectionStatus.getText();
        //System.out.println(status);
}
    
    
     
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMainText = new javax.swing.JLabel();
        btnNewProduct = new javax.swing.JButton();
        btnProductCatalog = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblNoAction1 = new javax.swing.JLabel();
        lblConnectionStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        lblMainText.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        lblMainText.setForeground(new java.awt.Color(102, 102, 102));
        lblMainText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainText.setText("Product Administration ");
        lblMainText.setToolTipText("");

        btnNewProduct.setBackground(new java.awt.Color(204, 204, 204));
        btnNewProduct.setForeground(new java.awt.Color(102, 102, 102));
        btnNewProduct.setText("New Product");
        btnNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewProductActionPerformed(evt);
            }
        });

        btnProductCatalog.setBackground(new java.awt.Color(204, 204, 204));
        btnProductCatalog.setForeground(new java.awt.Color(102, 102, 102));
        btnProductCatalog.setText("Product Catalog");
        btnProductCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductCatalogActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(204, 204, 204));
        btnExit.setForeground(new java.awt.Color(102, 102, 102));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblNoAction1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblNoAction1.setForeground(new java.awt.Color(153, 153, 153));
        lblNoAction1.setText(" Database Connection: ");

        lblConnectionStatus.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblConnectionStatus.setForeground(new java.awt.Color(0, 204, 0));
        lblConnectionStatus.setText("Connected");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMainText, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblNoAction1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblConnectionStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnProductCatalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnNewProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMainText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProductCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoAction1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(lblConnectionStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProductActionPerformed
        // create the dialog instance
        ProductEditor productEditorDialog = new ProductEditor(this, true, dao);

        // centre the dialog on the parent window
        productEditorDialog.setLocationRelativeTo(this);

        // make the dialog visible
        productEditorDialog.setVisible(true);
    }//GEN-LAST:event_btnNewProductActionPerformed

    private void btnProductCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductCatalogActionPerformed
        // create the dialog instance
        ProductCatalog ProductCatalogDialog = new ProductCatalog(this, true, dao);

        // centre the dialog on the parent window
        ProductCatalogDialog.setLocationRelativeTo(this);

        // make the dialog visible
        ProductCatalogDialog.setVisible(true);
    }//GEN-LAST:event_btnProductCatalogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNewProduct;
    private javax.swing.JButton btnProductCatalog;
    private javax.swing.JLabel lblConnectionStatus;
    private javax.swing.JLabel lblMainText;
    private javax.swing.JLabel lblNoAction1;
    // End of variables declaration//GEN-END:variables
}
