CREATE TABLE PRODUCTS(

ID INTEGER NOT NULL,
PRODUCTNAME VARCHAR NOT NULL,
DESCRIPTION VARCHAR,
CATEGORY VARCHAR NOT NULL,
PRICE DECIMAL(8,2) NOT NULL,
QUANTITY INTEGER NOT NULL,
constraint PK_PRODUCTS primary key (ID)
);

CREATE TABLE CUSTOMERS(

USERNAME VARCHAR NOT NULL,
NAME VARCHAR NOT NULL,
EMAIL VARCHAR NOT NULL,
ADDRESS VARCHAR NOT NULL,
PASSWORD VARCHAR NOT NULL,
CONSTRAINT PK_CUSTOMERS PRIMARY KEY (USERNAME)
);