CREATE TABLE PRODUCTS(

ID INTEGER NOT NULL,
PRODUCTNAME VARCHAR NOT NULL,
DESCRIPTION VARCHAR,
CATEGORY VARCHAR NOT NULL,
PRICE DECIMAL(8,2) NOT NULL,
QUANTITY INTEGER NOT NULL,
constraint PK_PRODUCTS primary key (ID)
);
